Models/Transaction.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace StockTradingSimulator.Models
{
    public class Transaction
    {
        public int _id { get; set; }
        public TransactionAccount[] transactionAccount { get; set; }

    }
    public class TransactionAccount
    {
        public int id { get; set; }
        public string userId { get; set; }
        public float InitialAmount { get; set; }

        public TransactionList[] transactionList { get; set; }

    }

    public class TransactionList
    {
        [Display(Name = "tId")]
        public int tId { get; set; }

        [Display(Name = "company")]
        public string company { get; set; }

        [Display(Name = "share")]
        public float share { get; set; }
        [Display(Name = "scrip")]
        public string scrip { get; set; }

        [Display(Name = "buyAt")]
        public float buyAt { get; set; }

        [Display(Name = "sellAt")]
        public float sellAt { get; set; }

        [Display(Name = "buyDatetime")]
        public string buyDatetime { get; set; }

        [Display(Name = "sellDatetime")]
        public string sellDatetime { get; set; }

    }
}

Models/TransactionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StockTradingSimulator.Models
{
    public class TransactionModel
    {
        public List<TransactionAccount> transactionAccount { get; set; }

        ///<summary>
        /// Gets or sets CurrentPageIndex.
        ///</summary>
        public int CurrentPageIndex { get; set; }

        ///<summary>
        /// Gets or sets PageCount.
        ///</summary>
        public int PageCount { get; set; }
    }
}

Controllers/DashboardController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using StockTradingSimulator.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace StockTradingSimulator.Controllers
{
    public class DashboardController : Controller
	{
        int CurrentPageIndex = 1;

        public ActionResult Index()
		{
			return View();
        }
        [HttpGet]
        public JsonResult TransactionDetails()
        {
            int maxRows = 10;
            ViewBag.BalanceAmount = "Your contact page.";
            ViewBag.CurrentStatus = "CurrentStatus";
            string jsonString = System.IO.File.ReadAllText(Server.MapPath("~/Data/transaction.json"));
            Transaction jsonObject = JsonConvert.DeserializeObject<Transaction>(jsonString);


            var filteredData = jsonObject.transactionAccount.Where(x => x.userId == "1")
                        .Skip((CurrentPageIndex - 1) * maxRows)
                        .Take(maxRows).ToList(); ;
            
            //TransactionModel transactionModel = new TransactionModel();
            //transactionModel.transactionAccount = (filteredData);
            //double pageCount = (double)((decimal)filteredData[0].transactionList.Count() / Convert.ToDecimal(maxRows));
            //transactionModel.PageCount = (int)Math.Ceiling(pageCount);
            //transactionModel.CurrentPageIndex = currentPageIndex;

            return Json(filteredData, JsonRequestBehavior.AllowGet);


        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockTradingSimulator.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return RedirectToAction("Index", "Dashboard");
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

Controllers/SuccessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockTradingSimulator.Controllers
{
    public class SuccessController : Controller
    {
        // GET: Success
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/TradingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using StockTradingSimulator.Models;

namespace StockTradingSimulator.Controllers
{
    public class TradingController : Controller
    {
        // GET: Trading
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Sell()
        {
            int maxRows = 10;
            ViewBag.BalanceAmount = "Your contact page.";
            ViewBag.CurrentStatus = "CurrentStatus";
            string jsonString = System.IO.File.ReadAllText(Server.MapPath("~/Data/transaction.json"));
            Transaction jsonObject = JsonConvert.DeserializeObject<Transaction>(jsonString);
           int scripID= Convert.ToInt32(Request.QueryString.Get("id"));

            var filteredData = jsonObject.transactionAccount.Where(x => x.userId == "1")
                                                .Take(maxRows).ToList();

            var scrip = filteredData[0].transactionList[scripID];

            return View(scrip);
        }
        public ActionResult Buy()
        {
            return View();
        }
    }
}

Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "www.compilemode.com";
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<style type="text/css">
    .red {
        color: red !important;
    }

    .blue {
        color: blue !important;
    }

    .green {
        color: green !important;
    }
</style>
<div style="margin-top:20px">
    @Html.Partial("Portfolio");
    @Html.Partial("TransactionDetails");
</div>

Views/Dashboard/Portfolio.cshtml
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<style>


</style>
<script>
    $(document).ready(function () {
        //Call EmpDetails jsonResult Method
        $.getJSON("Dashboard/TransactionDetails",
            function (json) {
                var tr;
                if (json.length > 0) {
                    var BalanceAmount = document.getElementById("BalanceAmount");
                    var CurrentStatus = document.getElementById("CurrentStatus");
                    var totalInvestment = 0;
                    var transactionList = json[0].transactionList;
                    var bdate, sdate;
                    //Append each row to html table
                    for (var i = 0; i < transactionList.length - 5; i++) {
                        tr = $('<tr/>');
                        tr.append("<td>" + transactionList[i].company + "</td>");
                        tr.append("<td>" + transactionList[i].scrip + "</td>");
                        tr.append("<td>" + transactionList[i].share + "</td>");
                        tr.append("<td>" + transactionList[i].buyAt + "</td>");
                        
                        if (transactionList[i].buyAt <= transactionList[i].sellAt) {
                            tr.append("<td class='green'>" + transactionList[i].sellAt + "</td>");
                        }
                        else {
                            tr.append("<td class='red'>" + transactionList[i].sellAt + "</td>");
                        }

                        tr.append("<td>" + ((transactionList[i].sellAt - transactionList[i].buyAt) * transactionList[i].share) + "</td>");
                        tr.append("<td><a href='/Trading/Sell?id=" + i.toString() + "'>Sell</a></td>");

                        $('.ptable').append(tr);
                        totalInvestment = totalInvestment + ((transactionList[i].sellAt - transactionList[i].buyAt) * transactionList[i].share);
                    }
                    BalanceAmount.innerText = json[0].InitialAmount + totalInvestment;
                    CurrentStatus.innerText = totalInvestment;

                }
            });
    });
</script>
<div class="jumbotron col-md-12">

    <div class="col-md-6">
        <h3>Balance Amount</h3>
        <p><span id="BalanceAmount"></span></p>
    </div>
    <div class="col-md-6">
        <h3>Overall Profit/Loss</h3>
        <p><span id="CurrentStatus" class='green'></span></p>
    </div>
</div>
<h2>Your Portfolio</h2>

<table class="ptable table-bordered table-condensed table-hover table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Company</th>
            <th>Scrip</th>
            <th>Share</th>
            <th>Buy At</th>
            <th>Current Price</th>
            <th>Profit/Loss</th>
            <th></th>

        </tr>
    </thead>
    <tbody></tbody>


</table>

Views/Dashboard/TransactionDetails.cshtml
<script src="~/Scripts/jquery-3.4.1.min.js"></script>

<script>
    $(document).ready(function () {
        //Call EmpDetails jsonResult Method
        $.getJSON("Dashboard/TransactionDetails",
            function (json) {
                var tr;
                if (json.length > 0) {
                    var BalanceAmount = document.getElementById("BalanceAmount");
                    var CurrentStatus = document.getElementById("CurrentStatus");
                    var totalInvestment = 0;
                    var transactionList = json[0].transactionList;
                    var bdate, sdate;
                    //Append each row to html table
                    for (var i = 0; i < transactionList.length; i++) {
                        tr = $('<tr/>');
                        tr.append("<td>" + transactionList[i].company + "</td>");
                        tr.append("<td>" + transactionList[i].share + "</td>");
                        tr.append("<td>" + transactionList[i].buyAt + "</td>");
                        if (transactionList[i].buyAt <= transactionList[i].sellAt) {
                            tr.append("<td class='green'>" + transactionList[i].sellAt + "</td>");
                        }
                        else {
                            tr.append("<td class='red'>" + transactionList[i].sellAt + "</td>");
                        }
                        bdate = new Date(transactionList[i].buyDatetime);
                        tr.append("<td>" + bdate.toDateString() + "</td>");
                        sdate = new Date(transactionList[i].sellDatetime);
                        tr.append("<td>" + sdate.toDateString() + "</td>");

                        tr.append("<td>" + ((transactionList[i].sellAt - transactionList[i].buyAt) * transactionList[i].share) + "</td>");

                        $('table').append(tr);
                        totalInvestment = totalInvestment + ((transactionList[i].sellAt - transactionList[i].buyAt) * transactionList[i].share);
                    }
                    BalanceAmount.innerText = json[0].InitialAmount;
                    CurrentStatus.innerText = totalInvestment;
                    if (totalInvestment < 0) {
                        CurrentStatus.classList.add('red');
                        CurrentStatus.classList.remove('green');
                    }
                }
            });
    });
</script>
<div class="jumbotron col-md-12">

    <div class="col-md-6">
        <h3>Balance Amount</h3>
        <p><span id="BalanceAmount">/span></p>
    </div>
    <div class="col-md-6">
        <h3>Overall Profit/Loss</h3>
        <p><span id="CurrentStatus" class='green'></span></p>
    </div>
</div>
<table class="table table-bordered table-condensed table-hover table-striped">
    <thead>
        <tr>
            <th>Company</th>
            <th>Share</th>
            <th>Buy At</th>
            <th>Sell At</th>
            <th>Buy Date</th>
            <th>Sell Date</th>
            <th>Profit/Loss</th>
        </tr>
    </thead>
    <tbody></tbody>

    
</table>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this ex1-master to provide additional information.</p>
<p>Use this area to provide Project information.</p>
<p>Use this area to provide Implementation information.</p>

<p>Use this area to provide Timeline information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    git add 8.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">Master is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting</h2>git
        <p>
            ASP.NET MVC gives you a powerful, -based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Trading Simulator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Stock Trading Simulator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="color:black">
                    <li >@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Dashboard", "Index", "Dashboard")</li>
                    <li>@Html.ActionLink("Trade", "Buy", "Trading")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <link href="~/Css/Style.css" rel="stylesheet" />
</body>
</html>

Views/Success/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Thank you!</h2>

<br /><br />
<h3> Your transaction has been successfully executed at current market price.</h3>

<br />

<h4><a href="/Dashboard">View your Portfolio</a></h4><br /><br /><br /><br />

Views/Trading/Buy.cshtml
@{
    ViewBag.Title = "Buy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Buy Shares</h2>
<br />
<style>

    p {
        
        width:300px !important;
    }
</style>

<h4>


    <p>Enter Scrip Code: </p><input type="text" style="width:200px" /><br /><br />

    <p> Enter Quantity to Buy :</p> <input type="text" style="width:200px" /><br /><br />
</h4>



<b><input type="button" style="width:200px" class="btn btn-primary" value="Buy" onclick="javascript:document.location='/success'" /></b>

Views/Trading/Sell.cshtml
@model StockTradingSimulator.Models.TransactionList


@{
    ViewBag.Title = "Sell";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sell Your Shares</h2>
<br />
<style>

    span {
    color: teal;}
</style>

<h4>
    Company :<span> @Html.DisplayFor(model => model.company) </span><br /><br />

    Scrip : <span>@Html.DisplayFor(model => model.scrip) </span><br /><br />

    Available to Sell : <span>@Html.DisplayFor(model => model.share)</span><br /><br />
</h4>


<h4>Please enter the quantity to sell:</h4><br />

<input type="text" style="width:200px"/>

<b><input type="button" style="width:200px" class="btn btn-primary" value="Sell"  onclick="javascript:document.location='/success'"/></b>